### ISSUE TITLE
Undefined index: direction 

### ISSUE THREAD

**Issue by odinuv** [keboola/processor-move-files#5]
Fatal error: Uncaught ErrorException: Undefined index: direction in \/code\/main.php:38\nStack trace:\n#0 \/code\/main.php(38): {closure}(8, 'Undefined index...', '\/code\/main.php', 38, Array)\n#1 {main}\n  thrown in \/code\/main.php on line 38"

**Comment by ondrejhlavacek** [comment]
Kdes na to narazil? Asi vím, čím to je, jen mě zajímá, kde se používá procesor :-)

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1517417168001056

**Comment by ondrejhlavacek** [comment]
supr, dík, jdu to hned fixnout.
